name: "Pull request"

on:
  pull_request:
    branches:
      - "main"
      - "release/**"

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yaml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
