name: "Release"

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yaml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install

      - run: poetry build
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry publish
