name: "Release"

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yaml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.6.1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install poetry dependencies
        run: poetry install

      - name: Build python package
        run: poetry build

      - name: Configure PyPi secrets
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Publish python package to PyPi
        run: poetry publish
